package com.jdm.http.webserver.model;

import junit.framework.TestCase;
import com.jdm.http.webserver.model.Password;
import com.jdm.http.webserver.model.Role;
import com.jdm.http.webserver.model.Permission;
import com.jdm.http.webserver.model.User;

import java.util.HashSet;

public class UserTest extends TestCase {
	
	public static final String USERNAME_1 = "Victor Hugo Martínez";
	public static final String USERNAME_2 = "Miguel Sánchez Barró";
	public static final String USER_ROLE_NAME = "basic";
	public static final String EDIT_PERMISSION = "edit";
	public static final String VIEW_PERMISSION = "view";
	private User user;
	private Password userPassword;
	private Role userRole;

	@Override
	protected void setUp() throws Exception {
		userPassword = Password.createFromUncrypted("qwerty");
		HashSet<Permission> permissions = new HashSet<Permission>();
		permissions.add(new Permission(EDIT_PERMISSION));
		userRole = new Role(USER_ROLE_NAME, permissions);
		user = new User(USERNAME_1, userPassword, userRole);
	}

	public void testAutoGeneratedUniqueId() {
		assertNotSame(user.getId(), new User(USERNAME_2, userPassword, userRole).getId());
	}

	public void testUserGetterMethods() {
		assertSame(USERNAME_1, user.getUsername());
		assertSame(userPassword, user.getPassword());
	}

	public void testGetRoleFromUser() {
		assertSame(userRole.getName(), user.getRoleName());
	}

	public void testValidatePermission() {
		assertTrue(user.hasPermission(new Permission(EDIT_PERMISSION)));
		assertFalse(user.hasPermission(new Permission(VIEW_PERMISSION)));
	}
}
